In [1]:
import numpy as np

In [3]:
import random
w = np.array(random.sample(range(1000), 12)) 
# одномерный массив из 12 случайных чисел от 1 до 1000
w = w.reshape((2,2,3)) # превратим w в трёхмерную матрицу
mat = w.transpose(0,2,1)
print(mat)

[[[724  35]
  [ 55 466]
  [600 568]]

 [[302 652]
  [167 877]
  [949 134]]]


In [4]:
# ДЗ
# Массив, который нужно было создать в предыдущей задаче
# хранится в переменной mat. 
# Превратите его в вертикальный вектор и напечатайте

w = mat.reshape(12, 1)
print(w)

[[724]
 [ 35]
 [ 55]
 [466]
 [600]
 [568]
 [302]
 [652]
 [167]
 [877]
 [949]
 [134]]


In [ ]:
#ДЗ
Задача: считайте данные из файла boston_houses.csv и посчитайте их средние значения.

Файл, из которого нужно считать данные, находится локально,
Первая строчка в файле — названия столбцов, 
остальные строки — числовые данные (то есть каждая строка, кроме первой,
состоит из последовательности вещественных чисел, разделённых запятыми).

Посчитайте и напечатайте вектор из средних значений вдоль столбцов входных данных. 
То есть если файл с входными данными выглядит как

a,b,c,d
1.5,3,4,6
2.5,2,7.5,4
3.5,1,3.5,2

то ответом будет

[ 2.5  2.   5.   4. ]

In [5]:
sbux = np.loadtxt("boston_houses", skiprows=1, delimiter=",") 
print(sbux.mean(axis=0))

[22.53280632  3.61352356 11.36363636  0.06916996  0.55469506  6.28463439
  3.79504269]


In [6]:
#      ДЗ (разминка)
#Создайте и напечатайте (с помощью функции print) 
#массив класса np.ndarray ширины 4 и высоты 3
#с двойками на главной диагонали и единицами на 
#первой диагонали над главной
#Обратите внимание на то, что мы используем Python 3,
#где print() принимает аргументы в скобках.
#Подсказка: простым путём может быть использование
#сложения и умножения на константу.
#просто подставьте нужные значение вместо ..

a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
print(b+2*a)


[[2. 1. 0. 0.]
 [0. 2. 1. 0.]
 [0. 0. 2. 1.]]
